

function mye(){
    let salam= document.querySelector(".heder");
let arr = ["Wie viele Jungs / Mädchen hast du bisher geküsst?","Bist du im Moment verliebt?","Hast du schon mal mit einer Frau / einem Mann rumgemacht?","Was war dein letzter Traum an den du dich erinnerst?","Hast du schon mal etwas geklaut?","Welches Tier wärst du am liebsten?","Wonach hast du als letztes gegoogelt?","Hast du schon mal sexy Bilder von der verschickt?","Würdest du mit jemandem knutschen, den du gerade erst kennengelernt hast?","Was findest du an dir am sexiesten?","Wofür hast du dich in letzter Zeit geschämt?","Was würdest du machen, wenn du für einen Tag unsichtbar wärst?","Wer in der Runde hat die schönsten Lippen?","Wer in der Runde hat den schönsten Hintern?","Welche Körperstellen rasierst du regelmäßig?","Was war deine letzte Lüge?","Was würdest du an deinem Körper verändern wenn du könntest?","Wann hattest du das letzte Mal Sex?","Mit wem hattest du das letzte Mal Sex?","Wenn du mit einer Person in der Runde schlafen müsstest, wen würdest du auswählen?","Wen in der Runde würdest du am ehesten küssen und warum?","Hattest du schon mal einen Dreier?","Hast du schon mal von einem Dreier geträumt?","Wann hattest du deinen letzten feuchten Traum","Was war der verrückteste Ort an dem du jemals Sex hattest?","Wie schafft man es am besten dich zu erregen?","Hast du schon mal mit jemandem aus der Runde geschlafen oder geknutscht?","Wen aus der Runde würdest du am liebsten nackt sehen wollen?","Hattest du schon mal einen One Night Stand?","Mit wie vielen Personen hattest du schon Sex?","Wieso bist du gut im Bett?","Wie kriegt man dich am besten rum?","Mit wem hattest du bisher das beste Sex Erlebnis deines Lebens?","Hast du schon mal Nacktbilder verschickt?","Gefällt dir Analsex?","Bist du eher dominant oder devot?","Welche Kleidung findest du besonders sexy an dir?","Hast du schon mal jemanden gefesselt oder wurst du schon mal gefesselt?","Hast du ein Sexspielzeug?",
];
    var randomIndex = Math.floor(Math.random() * arr.length);
    salam.innerHTML=arr[randomIndex]
    console.log(randomIndex)
}

function my2(){
    let salam= document.querySelector(".heder2");
    let arr2 =["Küss deinen linken/rechten Nachbarn auf die Wange oder den Mund.","Zeig uns deine Google Suchhistorie","Tausche dein Oberteil mit dem Spieler links/rechts von dir.","Leg dich in die Mitte, schließ die Augen und lass dich eine Minute lang von allen kitzeln.","Trinke einen Shot (wenn du Erwachsen bist).","Mach 10 Liegestütze.","Mach ein Selfie von der Gruppe und poste es auf Instagram/Facebook/Snapchat.","Mach der Person links/rechts von dir ein ernstgemeintes Kompliment.","Teste wessen Haare am besten riechen.","Imitiere eine Person aus der Runde. Die anderen müssen erraten, wer es ist.","Trink das Getränk von dem Spieler links/rechts von dir auf ex.","Tanze 60 Sekunden sexy zu einem Lied","Beleidige die Person links/rechts von dir. ","Zeig allen ein peinliches Foto von dir.","Flirte eine Runde mit der Person links/rechts von dir.","Schrei 20 schlimme Schimpfwörter.","Nimm einen Eiswürfel und steck ihn dir in die Hose.","Laufe wie bei Germany's Next Topmodel über den Catwalk.","Jaule 30 Sekunden lang wie ein Wolf - ohne zu lachen!","Zeig der Person gegenüber ein sexy Bild von dir.","Gib der Person links/rechts von dir einen Lapdance.","Flüster der Person gegenüber etwas heißes ins Ohr. ", "Küss der ersten Person des anderen Geschlechts rechts von dir zärtlich den Hals.","Zieh einer Person die Hose aus, ohne deine Hände zu benutzen.","Nimm deine Lieblingssexstellung ein und zeige sie den anderen.","Leg dich in die Mitte, schließ deine Augen und lass dir von einem zufälligen Mitspieler den Bauch küssen.","Twerke für eine Minute in der Mitte.","Geh aus dem Raum, zieh deine Unterwäsche aus, deine Hose wieder an und komm zurück","Sag jedem in der Runde, was an ihm sexy ist.","Schätze wer in der Runde am besten im Bett ist und warum.","Lass den Spieler links/rechts von dir etwas von deinem Hals lecken.","Erzähle allen, wieso Sex mit dir ein besonderes Erlebnis ist.","Bestimme einen Spieler, der dir einen Zungenkuss geben muss.","Führe den perfekten Blowjob mit einem Gegenstand deiner Wahl vor.","Such dir jemanden aus, den du eine Runde lang erotisch massieren musst.","Trinke einen kleinen Schluck von allen Getränken deiner Mitspieler.","Lass dir von einem Spieler deiner Wahl die Nippel lecken.","Mach einen Dreier-Kuss mit der Person links und rechts von dir.","Lass dir von einem Mitspieler deiner Wahl in die Hose fassen.","Lass dir von einem Mitspieler deiner Wahl in die Hose fassen."];
    var randomIndex2 = Math.floor(Math.random() * arr2.length);
    salam.innerHTML=arr2[randomIndex2]
    console.log(randomIndex2)
}
 
